### ISSUE TITLE
Speech synthesiser: Voice drop-down menu empty in Firefox 76 on Linux

### ISSUE THREAD

**Issue by LoLei** [mdn/web-speech-api#45]
The drop-down menu is empty in the Speech synthesiser [demo](https://mdn.github.io/web-speech-api/speak-easy-synthesis/).
When clicking play, `voiceSelect.selectedOptions[0] is undefined` shows up. I guess because I could not select a voice.

Firefox 76.0.1. (Linux 5.6.14-arch1-1)

![2020-05-25_13-46](https://user-images.githubusercontent.com/9076894/82810184-231eff00-9e8e-11ea-8dfa-4b473cfc1ee5.png)

Related to #4

**Comment by clemens-tolboom** [comment]
It is empty on **Linux**. Guess you do not have a speech synth on your system? At least on Firefox `76.0.1 (64-bit)` @ Mac I get

![Screenshot 2020-05-25 at 13 55 04](https://user-images.githubusercontent.com/371014/82810712-73e32780-9e8f-11ea-82c6-3649ec898f8f.png)

**Comment by LoLei** [comment]
Where is this dependency of a locally installed speech synthesizer mentioned?

The closest I can find is [here](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API):
>Speech synthesis is accessed via the SpeechSynthesis interface, a text-to-speech component that allows programs to read out their text content (**normally via the device's default speech synthesiser.**)

That is not transparent at all.

Also, it works in Chrome on the same Linux machine. I guess the dependency is built-in there?
And on Windows it also works out of the box in Firefox, with never knowingly having installed a speech synthesis software. Maybe that also comes with the OS.

In any case, I fixed it by installing:
* [Festival](http://www.cstr.ed.ac.uk/projects/festival/)
* [Speech Dispatcher](https://freebsoft.org/speechd)

And following the instructions [here](https://askubuntu.com/a/1042146/568802).
(I.e. making speech dispatcher use festival and running festival as a server.)

![2020-05-25_14-30](https://user-images.githubusercontent.com/9076894/82812897-45b41680-9e94-11ea-9658-d8242a2997e7.png)

**Comment by clemens-tolboom** [comment]
Maybe you could create a PR to give feedback when no speech voice is found?

**Comment by ralyodio** [comment]
I did not get this working on manjaro/arch either. I installed festival, speech-dispatcher and festival-freebsoft-utils

and it still is empty voices array in Firefox.

**Comment by ralyodio** [comment]
I tried following the instructions above and i still get this error:

```
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_slt_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_rms_cg
SIOD: unknown voice cmu_us_awb_cg
SIOD: unknown voice cmu_us_awb_cg
```

with festival
